name: publish
on:
  workflow_dispatch: # testing only, trigger manually to test it works
  push:
    branches:
    - main
    tags:
      - 'v*'
permissions:
  contents: write # To upload assets to release
  packages: write # To publish container images to GHCR
  # id-token: write # To use GitHub OIDC for AWS auth to publish to ECR
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'
        check-latest: true

    - uses: ko-build/setup-ko@v0.6

    - name: run ko build and publish image
      run: |
        ko build --bare \
          --platform=linux/amd64,linux/arm64 \
          --tags=latest,sha.${{ github.sha }}

    - name: run ko build and publish image
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        ko build --bare \
          --platform=linux/amd64,linux/arm64 \
          --tags=latest,sha.${{ github.sha }},${{ github.ref_name }}

    - name: Install syft
      uses: anchore/sbom-action/download-syft@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 # v0.18.0

    - name: Run GoReleaser Release
      # if: startsWith(github.ref, 'refs/tags/')
      id: run-goreleaser-release
      uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
      with:
        distribution: goreleaser
        version: latest
        args: 'release --clean'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
