name: publish
on:
  push:
    branches:
    - main
permissions:
  contents: read
  packages: write # To publish container images to GHCR
  id-token: write # To use GitHub OIDC for AWS auth to publish to ECR
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'
        check-latest: true
    - uses: ko-build/setup-ko@v0.6
    - run: ko build
