name: publish
on:
  push:
    branches:
    - main
    tags:
      - 'v*'
permissions:
  contents: read
  packages: write # To publish container images to GHCR
  # id-token: write # To use GitHub OIDC for AWS auth to publish to ECR
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-go@v4
      with:
        go-version: '1.22.3'
        check-latest: true

    - uses: ko-build/setup-ko@v0.6

    - name: run ko build and publish image
      run: |
        ko build --bare \
          --tags=latest,sha.${{ github.sha }}

    - name: run ko build and publish image
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        ko build --bare \
          --tags=latest,sha.${{ github.sha }},${{ github.ref_name }}
