name: publish
on:
  workflow_dispatch: # testing only, trigger manually to test it works
  push:
    branches:
    - main
    tags:
      - 'v*'
permissions:
  contents: write # To upload assets to release
  packages: write # To publish container images to GHCR
  # id-token: write # To use GitHub OIDC for AWS auth to publish to ECR
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Harden the runner (Audit all outbound calls)
      uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
      with:
        egress-policy: audit

    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0

    - uses: actions/setup-go@19bb51245e9c80abacb2e91cc42b33fa478b8639 # v4.2.1
      with:
        go-version: '1.23.5'
        check-latest: true

    - uses: ko-build/setup-ko@ace48d793556083a76f1e3e6068850c1f4a369aa # v0.6

    - name: run ko build and publish image
      run: |
        ko build --bare \
          --platform=linux/amd64,linux/arm64 \
          --tags=latest,sha.${{ github.sha }}

    - name: run ko build and publish image
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        ko build --bare \
          --platform=linux/amd64,linux/arm64 \
          --tags=latest,sha.${{ github.sha }},${{ github.ref_name }}

    - name: Install syft
      uses: anchore/sbom-action/download-syft@f325610c9f50a54015d37c8d16cb3b0e2c8f4de0 # v0.18.0

    - name: Run GoReleaser Snapshot
      if: ${{ !startsWith(github.ref, 'refs/tags/') }}
      id: run-goreleaser-snapshot
      uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
      with:
        distribution: goreleaser
        version: latest
        args: release --clean --snapshot --skip=sign
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GORELEASER_CURRENT_TAG: v0.0.0-snapshot-tag
        DOCKER_CONTEXT: default

    - name: Run GoReleaser Release
      if: startsWith(github.ref, 'refs/tags/')
      id: run-goreleaser-release
      uses: goreleaser/goreleaser-action@90a3faa9d0182683851fbfa97ca1a2cb983bfca3 # v6.2.1
      with:
        distribution: goreleaser
        version: latest
        args: 'release --clean'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
